### ISSUE TITLE
Import errors

### ISSUE THREAD

**Issue by ramashishb** [Koed00/django-q#147]
Hi,

I have added django_q in INSTALLED_APPS. All of Django's management commands are now throwing this error-

ValueError: Attempted relative import in non-package

Stack trace
```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/xxx/.virtualenvs/plweb/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/Users/xxx/.virtualenvs/plweb/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/Users/xxx/.virtualenvs/plweb/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/xxx/.virtualenvs/plweb/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/xxx/.virtualenvs/plweb/lib/python2.7/site-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/xxx/.virtualenvs/plweb/lib/python2.7/site-packages/django_q/apps.py", line 3, in <module>
    from .conf import Conf
```

Any idea?

**Comment by ramashishb** [comment]
My Django version is 1.8.9 and I am using Python 2.7.5 on Mac in case it helps.

**Comment by Eagllus** [comment]
@ramashishb is this still an issue?
