### ISSUE TITLE
apps.py: Attempted relative import with no known parent package

### ISSUE THREAD

**Issue by shacker** [Koed00/django-q#249]
Attempting to run `migrate` on a fresh pip install in Django 1.10.7, I got the error 

```
  File "/Users/me/.virtualenvs/proto/lib/python3.6/site-packages/django_q/apps.py", line 3, in <module>
    from .conf import Conf
ImportError: attempted relative import with no known parent package
```

I was able to fix this by directly editing `django_q/apps.py` and changing:

`from .conf import Conf`
to
`from django_q.conf import Conf`

I'd do a PR for this, but am not quite sure of what's going on since no one else seems to be experiencing it. Theories?

**Comment by shacker** [comment]
Is no one else experiencing this? I just hit it again with a fresh project. Would a simple PR be accepted with the change above?

**Comment by Legen7** [comment]
I have this error too. And after I fix the error by ur way,it raise an other error:`Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python27\CashSever\lib\site-packages\django\core\management\__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "C:\Python27\CashSever\lib\site-packages\django\core\management\__init__.py", line 341, in execute
    django.setup()
  File "C:\Python27\CashSever\lib\site-packages\django\__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Python27\CashSever\lib\site-packages\django\apps\registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "C:\Python27\CashSever\lib\site-packages\django\apps\config.py", line 123, in create
    import_module(entry)
  File "C:\Python27\Lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named base
`

**Comment by tawanda** [comment]
I also experienced the issue on django 1.11  and python 3.6.1

My solution was to put django_q as the last item in installed apps

```
INSTALLED_APPS = [
       ...,
       ...,
      'django_q'   # <-------last item in list
]
```

**Comment by Koed00** [comment]
I didn't see a PR for this, since I'm doing some updates. I'll see if I can fix some of the relative imports in the code for the next release.

**Comment by Eagllus** [comment]
Closing this issue because #264 has been merged.
If you still experiencing an issue please reopen this issue
