### ISSUE TITLE
Override the cluster’s timeout settings to None for task

### ISSUE THREAD

**Issue by josven** [Koed00/django-q#284]
In the cluster settings you can set the timeout to None. But if you set timeout to None in `django_q.tasks.async` you get a TypeError.

```
Traceback (most recent call last):
  File "python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "python3.6/site-packages/django_q/cluster.py", line 379, in worker
    timer.value = timer_value  # Busy
  File "<string>", line 11, in setvalue
TypeError: must be real number, not NoneType
```

**Comment by LeoQuote** [comment]
set the timeout to ``-1`` works for me , seems there's an error in the doc
