### ISSUE TITLE
from django_q.tasks import async - ImportError: cannot import name 'async'

### ISSUE THREAD

**Issue by DragosChirila** [Koed00/django-q#346]
Hi,

I have been using version 0.9.4, but after switching to 1.0.1 my Django project breaks.

Steps to reproduce the problem:
1. create a brand new Django project
2. install the requirements.txt
Django==1.11.20
django-q==1.0.1
3. pip freeze
arrow==0.13.1
blessed==1.15.0
Django==1.11.20
django-picklefield==2.0
django-q==1.0.1
python-dateutil==2.8.0
pytz==2018.9
six==1.12.0
wcwidth==0.1.7
4. added 'django_q' in settings.py
5. created an empty app - python manage.py startapp myapp
6. added this line inside myapp/models.py
from django_q.tasks import async
7. restart django and got the following error:
(ztest) ➜  zproj python manage.py runserver 0.0.0.0:8001
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f9490166d90>
Traceback (most recent call last):
  File "/var/local/envs/ztest/lib/python3.6/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/var/local/envs/ztest/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 116, in inner_run
    autoreload.raise_last_exception()
  File "/var/local/envs/ztest/lib/python3.6/site-packages/django/utils/autoreload.py", line 251, in raise_last_exception
    six.reraise(*_exception)
  File "/var/local/envs/ztest/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/var/local/envs/ztest/lib/python3.6/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/var/local/envs/ztest/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/var/local/envs/ztest/lib/python3.6/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/var/local/envs/ztest/lib/python3.6/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/var/local/envs/ztest/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/local/zproj/myapp/models.py", line 4, in <module>
    from django_q.tasks import async
ImportError: cannot import name 'async'

If going back to 0.9.4, the above works.

Any idea about this, am I missing something here?

Best Regards,
Dragos

**Comment by thinkwelltwd** [comment]
The reason is because `async` is a reserved keyword in python3.7. From the Readme of this project:

"
Tested with: Python 3.6. 3.7 Django 1.11.x and 2.1.x

Warning

Since Python 3.7 async became a reserved keyword and was refactored to async_task
"

**Comment by DragosChirila** [comment]
@thinkwelltwd Thank you for your response, I forgot to mention that I am running Python 3.6.6
