### ISSUE TITLE
"ERROR: invalid syntax (<unknown>, line 1)" when migrating from Python 2 to 3

### ISSUE THREAD

**Issue by tonysyu** [Koed00/django-q#357]
This may be specific to using the Django ORM as the queue backend.

When porting an existing app using `django-q` to Python 3, I noticed logging lines complaining about the following:

```
2019-05-06 09:49:42,167 ERROR django-q: invalid syntax (<unknown>, line 1) [in /usr/local/lib/python3.6/dist-packages/django_q/cluster.py:558, 140417530787648 (MainThread), 27943 (Process-1)]
```

That wasn't much to go on, so I edited the `logger.error(e)` of the `scheduler` function (line 558 corresponds to that line in `django-q` v0.9.4), to be `logger.exception(e)` and got the following message:
```
2019-05-06 09:52:12,859 ERROR django-q: invalid syntax (<unknown>, line 1) [in /usr/local/lib/python3.6/dist-packages/django_q/cluster.py:558, 140417530787648 (MainThread), 27943 (Process-1)]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django_q/cluster.py", line 506, in scheduler
    args = ast.literal_eval(s.args)
  File "/usr/lib/python3.6/ast.py", line 48, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/lib/python3.6/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    (320L,)
        ^
SyntaxError: invalid syntax
```

This error makes sense because `django-q` was storing integers (in this case, model ids) as long integers. While the following works in Python 2, it fails to parse in Python 3:
```
>>> import ast
>>> ast.literal_eval('(320L,)')
  File "<unknown>", line 1
    (320L,)
        ^
SyntaxError: invalid syntax
```

I think I'm going to have to write a custom migration on the `django-q` scheduled tasks table to migrate the data in any existing tasks to strip out the trailing `L` in integers. Are there better ways of handling this?

**Comment by tonysyu** [comment]
Asked on StackOverflow for more visibility: https://stackoverflow.com/questions/56014957/syntaxerror-with-pickled-integers-when-migrating-app-using-django-q-to-python-3
