### ISSUE TITLE
InterfaceError: connection already closed with sync: True

### ISSUE THREAD

**Issue by wgordon17** [Koed00/django-q#368]
Versions
```
django-q==1.0.1
Django==2.1.5
macOS 10.14.5
psql (PostgreSQL) 10.6
```

Settings
```
Q_CLUSTER = {
    'workers': 1,
    'sync': True
    'timeout': 3600,
    'save_limit': 5,
    'orm': 'default'
}
```

Error
```python
23:41:48 [Q] INFO MainProcess ready for work at 20124
23:41:48 [Q] INFO MainProcess processing [football-low-romeo-tennessee]
23:41:48 [Q] INFO MainProcess stopped doing work
23:41:48 [Q] INFO MainProcess monitoring at 20124
23:41:48 [Q] ERROR connection already closed
23:41:48 [Q] ERROR Failed [football-low-romeo-tennessee] - connection already closed : Traceback (most recent call last):
  File "/Users/wgordon/conda/envs/trip/lib/python3.6/site-packages/django/db/backends/base/base.py", line 234, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/Users/wgordon/conda/envs/trip/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 222, in create_cursor
    cursor = self.connection.cursor()
psycopg2.InterfaceError: connection already closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/wgordon/conda/envs/trip/lib/python3.6/site-packages/django_q/cluster.py", line 377, in worker
    res = f(*task['args'], **task['kwargs'])
  File "/Users/wgordon/Projects/trip/trip_apps/meetings/tasks.py", line 6, in send_action_email
    note = models.Note.objects.select_related('assignee', 'meeting').get(pk=note_id)
  File "/Users/wgordon/conda/envs/trip/lib/python3.6/site-packages/django/db/models/query.py", line 393, in get
    num = len(clone)
  File "/Users/wgordon/conda/envs/trip/lib/python3.6/site-packages/django/db/models/query.py", line 250, in __len__
    self._fetch_all()
  File "/Users/wgordon/conda/envs/trip/lib/python3.6/site-packages/django/db/models/query.py", line 1186, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/wgordon/conda/envs/trip/lib/python3.6/site-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/Users/wgordon/conda/envs/trip/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1063, in execute_sql
    cursor = self.connection.cursor()
  File "/Users/wgordon/conda/envs/trip/lib/python3.6/site-packages/django/db/backends/base/base.py", line 255, in cursor
    return self._cursor()
  File "/Users/wgordon/conda/envs/trip/lib/python3.6/site-packages/django/db/backends/base/base.py", line 234, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/Users/wgordon/conda/envs/trip/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/wgordon/conda/envs/trip/lib/python3.6/site-packages/django/db/backends/base/base.py", line 234, in _cursor
    return self._prepare_cursor(self.create_cursor(name))
  File "/Users/wgordon/conda/envs/trip/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 222, in create_cursor
    cursor = self.connection.cursor()
django.db.utils.InterfaceError: connection already closed
```

This seems to be specifically because I'm using making an ORM SQL call in my task function
```
File "/Users/wgordon/Projects/trip/trip_apps/meetings/tasks.py", line 6, in send_action_email
    note = models.Note.objects.select_related('assignee', 'meeting').get(pk=note_id)
```

Although, removing the ORM SQL call from the task function, I'm still getting an `InterfaceError: connection already closed` error in my view code that runs after the task (since this is forced synchronous).

**Comment by wgordon17** [comment]
I'm also getting this error from MS SQL with

```
django-q==1.0.1
Django==2.1.9
django-pyodbc-azure==2.1.0.0
```

@Koed00 any insights here? I'd love to use `django-q`, it's significantly easier than Celery, however I can't get past this issue _or_ #367

**Comment by wgordon17** [comment]
Ok, with #367 finally figured out (_stupid IDEs_), I can keep work with `django-q` now (🎉)! I would still like to be able to run with `sync: True` (turning off debugging in PyCharm didn't help with this one).
