### ISSUE TITLE
Qcluster running well in an AWS EC2 instance but not in a docker container on the same machine

### ISSUE THREAD

**Issue by classifaddict** [Koed00/django-q#432]
Linux 3a697bfc2fe1 4.14.171-136.231.amzn2.x86_64 
Python==3.8.1
Django==3.0.5
Django_Q==1.2.1
PyMySQL==0.9.3

Q_CLUSTER = {
    'name': 'DjangORM',
    'workers': 1,
    'timeout': None,
    'retry': 14400,
    'queue_limit': 50,
    'bulk': 10,
    'orm': 'default'
}

ENTRYPOINT exec /home/ssm-user/IPCPUB_AWS/venv/bin/python /home/ssm-user/IPCPUB_AWS/manage.py qcluster --pythonpath /home/ssm-user/IPCPUB_AWS --settings ipcpub.settings

21:16:23 [Q] INFO Q Cluster foxtrot-lactose-fix-hotel starting.
21:16:23 [Q] INFO Process-1:1 ready for work at 42
21:16:23 [Q] INFO Process-1 guarding cluster foxtrot-lactose-fix-hotel
21:16:23 [Q] INFO Process-1:3 pushing tasks at 44
21:16:23 [Q] INFO Q Cluster foxtrot-lactose-fix-hotel running.
21:16:23 [Q] INFO Process-1:2 monitoring at 43
--- Logging error ---
Traceback (most recent call last):
  File "/home/ssm-user/IPCPUB_AWS/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ssm-user/IPCPUB_AWS/venv/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "/home/ssm-user/IPCPUB_AWS/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/ssm-user/IPCPUB_AWS/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/ssm-user/IPCPUB_AWS/venv/lib/python3.8/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/ssm-user/IPCPUB_AWS/venv/lib/python3.8/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/ssm-user/IPCPUB_AWS/venv/lib/python3.8/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/ssm-user/IPCPUB_AWS/venv/lib/python3.8/site-packages/pymysql/connections.py", line 657, in _read_packet
    packet_header = self._read_bytes(4)
  File "/home/ssm-user/IPCPUB_AWS/venv/lib/python3.8/site-packages/pymysql/connections.py", line 706, in _read_bytes
    raise err.OperationalError(
pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ssm-user/IPCPUB_AWS/venv/lib/python3.8/site-packages/django_q/cluster.py", line 329, in pusher
    task_set = broker.dequeue()
  File "/home/ssm-user/IPCPUB_AWS/venv/lib/python3.8/site-packages/django_q/brokers/orm.py", line 65, in dequeue
    if tasks:
  File "/home/ssm-user/IPCPUB_AWS/venv/lib/python3.8/site-packages/django/db/models/query.py", line 280, in __bool__
    self._fetch_all()
  File "/home/ssm-user/IPCPUB_AWS/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/ssm-user/IPCPUB_AWS/venv/lib/python3.8/site-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/ssm-user/IPCPUB_AWS/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1151, in execute_sql
    cursor.execute(sql, params)
  File "/home/ssm-user/IPCPUB_AWS/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/ssm-user/IPCPUB_AWS/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/ssm-user/IPCPUB_AWS/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/ssm-user/IPCPUB_AWS/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ssm-user/IPCPUB_AWS/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ssm-user/IPCPUB_AWS/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ssm-user/IPCPUB_AWS/venv/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 74, in execute
    return self.cursor.execute(query, args)
  File "/home/ssm-user/IPCPUB_AWS/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/ssm-user/IPCPUB_AWS/venv/lib/python3.8/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/ssm-user/IPCPUB_AWS/venv/lib/python3.8/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/ssm-user/IPCPUB_AWS/venv/lib/python3.8/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/ssm-user/IPCPUB_AWS/venv/lib/python3.8/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/ssm-user/IPCPUB_AWS/venv/lib/python3.8/site-packages/pymysql/connections.py", line 657, in _read_packet
    packet_header = self._read_bytes(4)
  File "/home/ssm-user/IPCPUB_AWS/venv/lib/python3.8/site-packages/pymysql/connections.py", line 706, in _read_bytes
    raise err.OperationalError(
django.db.utils.OperationalError: (2013, 'Lost connection to MySQL server during query')

**Comment by classifaddict** [comment]
Hello,
I really tried hard to figure out what is happening but now I'm stuck.
Is there any way to debug qcluster startup?
I really like Django_Q and don't want to go back to RQ.
Thanks in advance for any clue or help.

**Comment by edouardtheron** [comment]
Maybe a problem of network interface?
Have you tried to switch the IP to `0.0.0.0` instead of `127.0.0.1` or `localhost`?

**Comment by classifaddict** [comment]
Well, in fact it seems that the service is working properly despite that error message.
Qmonitor seems to work as well but not qinfo:
(venv) bash-4.2# python manage.py qinfo
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/ssm-user/IPCPUB_AWS/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/ssm-user/IPCPUB_AWS/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ssm-user/IPCPUB_AWS/venv/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ssm-user/IPCPUB_AWS/venv/lib/python3.8/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/home/ssm-user/IPCPUB_AWS/venv/lib/python3.8/site-packages/django_q/management/commands/qinfo.py", line 51, in handle
    info()
  File "/home/ssm-user/IPCPUB_AWS/venv/lib/python3.8/site-packages/django_q/monitor.py", line 200, in info
    exec_time = last_tasks.aggregate(
  File "/home/ssm-user/IPCPUB_AWS/venv/lib/python3.8/site-packages/django/db/models/query.py", line 384, in aggregate
    return query.get_aggregation(self.db, kwargs)
  File "/home/ssm-user/IPCPUB_AWS/venv/lib/python3.8/site-packages/django/db/models/sql/query.py", line 507, in get_aggregation
    result = next(compiler.apply_converters((result,), converters))
  File "/home/ssm-user/IPCPUB_AWS/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1095, in apply_converters
    value = converter(value, expression, connection)
  File "/home/ssm-user/IPCPUB_AWS/venv/lib/python3.8/site-packages/django/db/backends/mysql/operations.py", line 265, in convert_datetimefield_value
    value = timezone.make_aware(value, self.connection.timezone)
  File "/home/ssm-user/IPCPUB_AWS/venv/lib/python3.8/site-packages/django/utils/timezone.py", line 270, in make_aware
    return timezone.localize(value, is_dst=is_dst)
  File "/home/ssm-user/IPCPUB_AWS/venv/lib/python3.8/site-packages/pytz/__init__.py", line 237, in localize
    if dt.tzinfo is not None:
AttributeError: 'decimal.Decimal' object has no attribute 'tzinfo'

There is probably a problem with Aurora MySql seetings.
