### ISSUE TITLE
python manage.py qinfo (error)

### ISSUE THREAD

**Issue by bee-payments** [Koed00/django-q#439]
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/cosmo9able/bee_env/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/cosmo9able/bee_env/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/cosmo9able/bee_env/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/cosmo9able/bee_env/lib/python3.8/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/home/cosmo9able/bee_env/lib/python3.8/site-packages/django_q/management/commands/qinfo.py", line 51, in handle
    info()
  File "/home/cosmo9able/bee_env/lib/python3.8/site-packages/django_q/monitor.py", line 200, in info
    exec_time = last_tasks.aggregate(
  File "/home/cosmo9able/bee_env/lib/python3.8/site-packages/django/db/models/query.py", line 384, in aggregate
    return query.get_aggregation(self.db, kwargs)
  File "/home/cosmo9able/bee_env/lib/python3.8/site-packages/django/db/models/sql/query.py", line 508, in get_aggregation
    result = next(compiler.apply_converters((result,), converters))
  File "/home/cosmo9able/bee_env/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1095, in apply_converters
    value = converter(value, expression, connection)
  File "/home/cosmo9able/bee_env/lib/python3.8/site-packages/django/db/backends/mysql/operations.py", line 265, in convert_datetimefield_value
    value = timezone.make_aware(value, self.connection.timezone)
  File "/home/cosmo9able/bee_env/lib/python3.8/site-packages/django/utils/timezone.py", line 270, in make_aware
    return timezone.localize(value, is_dst=is_dst)
  File "/home/cosmo9able/bee_env/lib/python3.8/site-packages/pytz/__init__.py", line 237, in localize
    if dt.tzinfo is not None:
AttributeError: 'decimal.Decimal' object has no attribute 'tzinfo'

**Comment by zodman** [comment]
duplicate #339
