### ISSUE TITLE
ERROR: django-picklefield 3.0.1 has requirement Django>=2.2, but you'll have django 1.11.10 which is incompatible.

### ISSUE THREAD

**Issue by MirzaBaig715** [Koed00/django-q#445]
Hi I am using Django 1.11.10 with Python 3.6. I installed django-q[sentry]==0.9.4 but it is giving me error. Please tell me what should be the solution with Django 1.11.10?  @Koed00 Thanks in advance!

`Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/usr/local/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.6/site-packages/django/apps/config.py", line 120, in create
    mod = import_module(mod_path)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
 File "/usr/local/lib/python3.6/site-packages/django_q/apps.py", line 3, in <module>
    from django_q.conf import Conf
  File "/usr/local/lib/python3.6/site-packages/django_q/conf.py", line 213, in <module>
    Reporter = entry.load()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2443, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2466, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (Django 1.11.10 (/usr/local/lib/python3.6/site-packages), Requirement.parse('Django>=2.2'), {'django-picklefield'})`

**Comment by Djailla** [comment]
Upgrade Django ? Django 1.11 is deprecated.

**Comment by Koed00** [comment]
You could try installing django-picklefield 2.1.1 and see if that works.

I do agree with Djailla that you should probably start planning your upgrade to Django 3 at this point in time.

**Comment by MirzaBaig715** [comment]
I had to downgrade the django-picklefield version and it works. @Djailla @Koed00 surely we will be plan towards upgrading Django.

**Comment by Djailla** [comment]
@MirzaBaig715 can you close the issue then ?
