### ISSUE TITLE
django.db.utils.OperationalError: server closed the connection unexpectedly

### ISSUE THREAD

**Issue by 9126consulting** [Koed00/django-q#486]
### Environment
4.19.0-8-amd64 #1 SMP Debian 4.19.98-1+deb10u1 (2020-04-27) x86_64 GNU/Linux

Django==3.1.2
django-q==1.3.4
psycopg2-binary==2.8.6 (Postgres 12, AWS RDS)

### Error
psycopg2.OperationalError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/charry/charryenv/lib/python3.7/site-packages/django_q/cluster.py", line 340, in pusher
    task_set = broker.dequeue()
  File "/home/charry/charryenv/lib/python3.7/site-packages/django_q/brokers/orm.py", line 67, in dequeue
    if tasks:
  File "/home/charry/charryenv/lib/python3.7/site-packages/django/db/models/query.py", line 291, in __bool__
    self._fetch_all()
  File "/home/charry/charryenv/lib/python3.7/site-packages/django/db/models/query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/charry/charryenv/lib/python3.7/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/charry/charryenv/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "/home/charry/charryenv/lib/python3.7/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/charry/charryenv/lib/python3.7/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/charry/charryenv/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/charry/charryenv/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/charry/charryenv/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.OperationalError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/logging/handlers.py", line 917, in emit
    msg = self.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/charry/charryenv/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/charry/charryenv/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/charry/charryenv/lib/python3.7/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/charry/charryenv/lib/python3.7/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/home/charry/charryenv/lib/python3.7/site-packages/django_q/management/commands/qcluster.py", line 22, in handle
    q.start()
  File "/home/charry/charryenv/lib/python3.7/site-packages/django_q/cluster.py", line 75, in start
    self.sentinel.start()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.7/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_fork.py", line 74, in _launch
    code = process_obj._bootstrap()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/charry/charryenv/lib/python3.7/site-packages/django_q/cluster.py", line 165, in __init__
    self.start()
  File "/home/charry/charryenv/lib/python3.7/site-packages/django_q/cluster.py", line 170, in start
    self.guard()
  File "/home/charry/charryenv/lib/python3.7/site-packages/django_q/cluster.py", line 276, in guard
    self.reincarnate(self.pusher)
  File "/home/charry/charryenv/lib/python3.7/site-packages/django_q/cluster.py", line 218, in reincarnate
    self.pusher = self.spawn_pusher()
  File "/home/charry/charryenv/lib/python3.7/site-packages/django_q/cluster.py", line 198, in spawn_pusher
    return self.spawn_process(pusher, self.task_queue, self.event_out, self.broker)
  File "/home/charry/charryenv/lib/python3.7/site-packages/django_q/cluster.py", line 194, in spawn_process
    p.start()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.7/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_fork.py", line 74, in _launch
    code = process_obj._bootstrap()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/charry/charryenv/lib/python3.7/site-packages/django_q/cluster.py", line 342, in pusher
    logger.error(e, traceback.format_exc())

**Comment by 9126consulting** [comment]
works with local Postgres DB, but not with AWS RDS

**Comment by 9126consulting** [comment]
works with Django-q v1.0.2
not working since Django-q v1.1.0

Scheduler changed from:
`
def scheduler(broker=None):
    """
    Creates a task from a schedule at the scheduled time and schedules next run
    """
    if not broker:
        broker = get_broker()
    db.close_old_connections()
    try:
        for s in Schedule.objects.exclude(repeats=0).filter(next_run__lt=timezone.now()):
`

to

`def scheduler(broker=None):
    """
    Creates a task from a schedule at the scheduled time and schedules next run
    """
    if not broker:
        broker = get_broker()
    close_old_django_connections()
    try:
        with db.transaction.atomic():
            for s in Schedule.objects.select_for_update().exclude(repeats=0).filter(next_run__lt=timezone.now()):
`

So it seams the issue is related to transaction settings of my Postgres server or client. It works with a standalone Postgres installation, but not with a Postgres AWS Multizone RDS.

**Comment by sperrys** [comment]
Same here. Working fine locally, but not with provisioned heroku postgres.

**Comment by ricardochaves** [comment]
Not working with docker image `postgres:10.1-alpine`

**Comment by maxking** [comment]
I had a similar problem with postgres:9.6-alpine image and Djang-q==1.3.4 and Django=2.2.x (whatever latest is).

It was fixed by setting the connection max age to 0:
```
{'default': {'ATOMIC_REQUESTS': False,
             'AUTOCOMMIT': True,
             'CONN_MAX_AGE': 0,
             'ENGINE': 'django.db.backends.postgresql_psycopg2',
             'HOST': 'database',
             'NAME': 'mailmandb',
             'OPTIONS': {},
             'PASSWORD': '',
             'PORT': '',
             'TEST': {'CHARSET': None,
                      'COLLATION': None,
                      'MIGRATE': True,
                      'MIRROR': None,
                      'NAME': None},
             'TIME_ZONE': None,
             'USER': 'mailman'}}
```

This is my complete `settings.DATABASE` value. From above comments, it does seem like something to do with connection parameters or transaction settings in Postgres. 

Not sure the rest of the Django apps work but Django-q doesn't with a non-zero value of `conn_max_age`.  I tried setting it to `None` or some absolute value (600, previously) and I got similar error tracebacks as mentioned above.

**Comment by EyalEliyahu** [comment]
I'm having the same situation as @maxking
Any solution besides setting CONN_MAX_AGE to 0? 
also, any insights about how it'll affect my server performance?

EDIT:
I also found a workaround by running ׳django.db.connection.connect()׳ at the start of my async_task callback, still trying to figure out if this can be fixed at the root level
