### ISSUE TITLE
SQL errors when running tasks and viewing successful/failed tasks

### ISSUE THREAD

**Issue by FilipPruszekArrow** [Koed00/django-q#496]
Django == 3.1.4
django-mssql-backend == 2.8.1
Python == 3.9.1
SQL server == 2017 v15.0.2000.5

getting sql errors in qcluster console on each task run:
```
10:14:43 [Q] ERROR ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]An expression of non-boolean type specified in a context where a condition is expected, near 'success'. (4145) (SQLExecDirectW)")
```
and when accessing django q sites in django admin:
```
Environment:


Request Method: GET
Request URL: http://localhost:8000/admin/django_q/success/

Django Version: 3.1.4
Python Version: 3.9.1
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'django_cleanup.apps.CleanupConfig',
 'django_q',
 'social_django',
 'crispy_forms',
 'widget_tweaks',
 'django_summernote',
 'users',
 'dashboard',
 'changelog']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "C:\dev_stor\ps-dev_env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\dev_stor\ps-dev_env\lib\site-packages\sql_server\pyodbc\base.py", line 553, in execute
    return self.cursor.execute(sql, params)

The above exception (('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]An expression of non-boolean type specified in a context where a condition is expected, near 'AND'. (4145) (SQLExecDirectW)")) was the direct cause of the following exception:
  File "C:\dev_stor\ps-dev_env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\dev_stor\ps-dev_env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\dev_stor\ps-dev_env\lib\site-packages\django\contrib\admin\options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\dev_stor\ps-dev_env\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\dev_stor\ps-dev_env\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\dev_stor\ps-dev_env\lib\site-packages\django\contrib\admin\sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "C:\dev_stor\ps-dev_env\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\dev_stor\ps-dev_env\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\dev_stor\ps-dev_env\lib\site-packages\django\contrib\admin\options.py", line 1693, in changelist_view
    cl = self.get_changelist_instance(request)
  File "C:\dev_stor\ps-dev_env\lib\site-packages\django\contrib\admin\options.py", line 735, in get_changelist_instance
    return ChangeList(
  File "C:\dev_stor\ps-dev_env\lib\site-packages\django\contrib\admin\views\main.py", line 100, in __init__
    self.get_results(request)
  File "C:\dev_stor\ps-dev_env\lib\site-packages\django\contrib\admin\views\main.py", line 235, in get_results
    result_count = paginator.count
  File "C:\dev_stor\ps-dev_env\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\dev_stor\ps-dev_env\lib\site-packages\django\core\paginator.py", line 94, in count
    return c()
  File "C:\dev_stor\ps-dev_env\lib\site-packages\django\db\models\query.py", line 411, in count
    return self.query.get_count(using=self.db)
  File "C:\dev_stor\ps-dev_env\lib\site-packages\django\db\models\sql\query.py", line 515, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "C:\dev_stor\ps-dev_env\lib\site-packages\django\db\models\sql\query.py", line 500, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "C:\dev_stor\ps-dev_env\lib\site-packages\django\db\models\sql\compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "C:\dev_stor\ps-dev_env\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "C:\dev_stor\ps-dev_env\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\dev_stor\ps-dev_env\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\dev_stor\ps-dev_env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\dev_stor\ps-dev_env\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\dev_stor\ps-dev_env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\dev_stor\ps-dev_env\lib\site-packages\sql_server\pyodbc\base.py", line 553, in execute
    return self.cursor.execute(sql, params)

Exception Type: ProgrammingError at /admin/django_q/success/
Exception Value: ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]An expression of non-boolean type specified in a context where a condition is expected, near 'AND'. (4145) (SQLExecDirectW)")
```
```
Environment:


Request Method: GET
Request URL: http://localhost:8000/admin/django_q/failure/

Django Version: 3.1.4
Python Version: 3.9.1
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'django_cleanup.apps.CleanupConfig',
 'django_q',
 'social_django',
 'crispy_forms',
 'widget_tweaks',
 'django_summernote',
 'users',
 'dashboard',
 'changelog']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "C:\dev_stor\ps-dev_env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\dev_stor\ps-dev_env\lib\site-packages\sql_server\pyodbc\base.py", line 553, in execute
    return self.cursor.execute(sql, params)

The above exception (('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]An expression of non-boolean type specified in a context where a condition is expected, near 'success'. (4145) (SQLExecDirectW)")) was the direct cause of the following exception:
  File "C:\dev_stor\ps-dev_env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\dev_stor\ps-dev_env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\dev_stor\ps-dev_env\lib\site-packages\django\contrib\admin\options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\dev_stor\ps-dev_env\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\dev_stor\ps-dev_env\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\dev_stor\ps-dev_env\lib\site-packages\django\contrib\admin\sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "C:\dev_stor\ps-dev_env\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\dev_stor\ps-dev_env\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\dev_stor\ps-dev_env\lib\site-packages\django\contrib\admin\options.py", line 1693, in changelist_view
    cl = self.get_changelist_instance(request)
  File "C:\dev_stor\ps-dev_env\lib\site-packages\django\contrib\admin\options.py", line 735, in get_changelist_instance
    return ChangeList(
  File "C:\dev_stor\ps-dev_env\lib\site-packages\django\contrib\admin\views\main.py", line 100, in __init__
    self.get_results(request)
  File "C:\dev_stor\ps-dev_env\lib\site-packages\django\contrib\admin\views\main.py", line 235, in get_results
    result_count = paginator.count
  File "C:\dev_stor\ps-dev_env\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\dev_stor\ps-dev_env\lib\site-packages\django\core\paginator.py", line 94, in count
    return c()
  File "C:\dev_stor\ps-dev_env\lib\site-packages\django\db\models\query.py", line 411, in count
    return self.query.get_count(using=self.db)
  File "C:\dev_stor\ps-dev_env\lib\site-packages\django\db\models\sql\query.py", line 515, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "C:\dev_stor\ps-dev_env\lib\site-packages\django\db\models\sql\query.py", line 500, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "C:\dev_stor\ps-dev_env\lib\site-packages\django\db\models\sql\compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "C:\dev_stor\ps-dev_env\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "C:\dev_stor\ps-dev_env\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\dev_stor\ps-dev_env\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\dev_stor\ps-dev_env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\dev_stor\ps-dev_env\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\dev_stor\ps-dev_env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\dev_stor\ps-dev_env\lib\site-packages\sql_server\pyodbc\base.py", line 553, in execute
    return self.cursor.execute(sql, params)

Exception Type: ProgrammingError at /admin/django_q/failure/
Exception Value: ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]An expression of non-boolean type specified in a context where a condition is expected, near 'success'. (4145) (SQLExecDirectW)")
```

**Comment by FilipPruszekArrow** [comment]
Issue Solved

Turned out this is Django 3.1/mssql issue.
https://stackoverflow.com/questions/65190586/object-filter-error-using-boolean-fields
