### ISSUE TITLE
Great product

### ISSUE THREAD

**Issue by jyoost** [Koed00/django-q#522]
First, this is a great product.

I have used django celery beat.  This is more straight forward approach.

My question is :

I am running this on the new app platform on digital ocean. They have no profile like heroku.

It is deployed as a docker container but you must put the command to run in manually.

I can not get both the uwsgi and qcluster to run at deploy. This is such a nice inclusive package, that it would be great to start everything at once.

Any suggestions ?

**Comment by Koed00** [comment]
I am hoping someone will have done this before and will share their setup with the community.

If not, I could give it a try myself but I am limited in my time with these things.

**Comment by Koed00** [comment]
Even better :)

**Comment by jyoost** [comment]
I am working with some engineers at digital ocean, hopefully we will figure this out.

The app platform on digital ocean is awesome. It is pretty new and they are making it better all the time.

**Comment by Koed00** [comment]
You probably will have to create a dockerfile that is similar to the django dockerfile and then set the CMD to python and Qcluster.
Then include that dockerfile as the worker service in docker-compose.

**Comment by BoPeng** [comment]
[cookiecutter-django](https://github.com/pydanny/cookiecutter-django) has a [docker-compose set up for celery](https://github.com/pydanny/cookiecutter-django/tree/master/%7B%7Bcookiecutter.project_slug%7D%7D/compose/production/django) . There are some scripts for celery, flower etc in its docker file. I have tried this setup on digitalocean and can confirm that it works, so we could just adapt it for django-q.

https://github.com/pydanny/cookiecutter-django/blob/a18ccd35238745c588281b1436807c65ccd3c5d6/%7B%7Bcookiecutter.project_slug%7D%7D/compose/production/django/Dockerfile#L45-L59

**Comment by guettli** [comment]
@jyoost I have not done it yet, but I think you can use Honcho (or a similar tool) to start the django web-server and django-q in one container. Related blog: https://www.cloudbees.com/blog/using-honcho-create-multi-process-docker-container/

**Comment by jyoost** [comment]
@guettli  my solution was to package django-q in with a django project and deploy it with the least amount system configuration possible. Keeping it as simple as possible.

My solution with a DOfile on digital ocean does this. With no requirements outside of the django package.

**Comment by guettli** [comment]
@jyoost what is a DOfile? I googled for it, but found no useful answer.

**Comment by BoPeng** [comment]
Must be something Digital ocean (DO) specific.

**Comment by jyoost** [comment]
If you read back in this thread, I made it up 😁.

I describe what is in it, I did not want it to be confused with Procfile for heroku.

**Comment by stackbomb** [comment]
Hey there,
I am trying to deploy two components on DigitalOcean App Platform.
The first one is a simple Django app, and I was able to deploy it with no issues.
The second one is Django Q deployed as a worker in App Platform. The run command is: `python manage.py qcluster`

This is what I get in the logs:
```
worker | 2021-04-28 16:38:02 Traceback (most recent call last):
worker | 2021-04-28 16:38:02   File "manage.py", line 21, in <module>
worker | 2021-04-28 16:38:02     main()
worker | 2021-04-28 16:38:02   File "manage.py", line 17, in main
worker | 2021-04-28 16:38:02     execute_from_command_line(sys.argv)
worker | 2021-04-28 16:38:02   File "/workspace/.heroku/python/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
worker | 2021-04-28 16:38:02     utility.execute()
worker | 2021-04-28 16:38:02   File "/workspace/.heroku/python/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
worker | 2021-04-28 16:38:02     self.fetch_command(subcommand).run_from_argv(self.argv)
worker | 2021-04-28 16:38:02   File "/workspace/.heroku/python/lib/python3.7/site-packages/django/core/management/base.py", line 328, in run_from_argv
worker | 2021-04-28 16:38:02     self.execute(*args, **cmd_options)
worker | 2021-04-28 16:38:02   File "/workspace/.heroku/python/lib/python3.7/site-packages/django/core/management/base.py", line 369, in execute
worker | 2021-04-28 16:38:02     output = self.handle(*args, **options)
worker | 2021-04-28 16:38:02   File "/workspace/.heroku/python/lib/python3.7/site-packages/django_q/management/commands/qcluster.py", line 22, in handle
worker | 2021-04-28 16:38:02     q.start()
worker | 2021-04-28 16:38:02   File "/workspace/.heroku/python/lib/python3.7/site-packages/django_q/cluster.py", line 53, in start
worker | 2021-04-28 16:38:02     self.stop_event = Event()
worker | 2021-04-28 16:38:02   File "/workspace/.heroku/python/lib/python3.7/multiprocessing/context.py", line 92, in Event
worker | 2021-04-28 16:38:02     return Event(ctx=self.get_context())
worker | 2021-04-28 16:38:02   File "/workspace/.heroku/python/lib/python3.7/multiprocessing/synchronize.py", line 324, in __init__
worker | 2021-04-28 16:38:02     self._cond = ctx.Condition(ctx.Lock())
worker | 2021-04-28 16:38:02   File "/workspace/.heroku/python/lib/python3.7/multiprocessing/context.py", line 67, in Lock
worker | 2021-04-28 16:38:02     return Lock(ctx=self.get_context())
worker | 2021-04-28 16:38:02   File "/workspace/.heroku/python/lib/python3.7/multiprocessing/synchronize.py", line 162, in __init__
worker | 2021-04-28 16:38:02     SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
worker | 2021-04-28 16:38:02   File "/workspace/.heroku/python/lib/python3.7/multiprocessing/synchronize.py", line 59, in __init__
worker | 2021-04-28 16:38:02     unlink_now)
worker | 2021-04-28 16:38:02 OSError: [Errno 38] Function not implemented
worker | 2021-04-28 16:38:02 Sentry is attempting to send 0 pending error messages
worker | 2021-04-28 16:38:02 Waiting up to 2 seconds
worker | 2021-04-28 16:38:02 Press Ctrl-C to quit
```

Is it possible to deploy separately django and django q on app platform? On Heroku I was able to do this by specifying in Procfile the `worker` line. 
If I understand correctly, @jyoost is deploying both django and the workers in the same component. Am I right?
Thanks!

**Comment by jyoost** [comment]
If you read the above thread I give detailed instructions on exactly how to
do this.

**Comment by jyoost** [comment]
Make sure your command in the dashboard is bash DOfile and that the deploy completes and does not roll back to the previous version.

**Comment by stackbomb** [comment]
Hey @jyoost , tried to deploy a single component with the DOfile as you have described but when I go to the console to check if the worker is live doing `python manage.py qinfo` Or `python manage.py qmonitor` I cannot see the clusters.

I have also tried to upgrade the machine to higher CPU number but still no luck. 
Could you confirm you are seeing the clusters by running the commands I have posted? Thank you!

**Comment by jyoost** [comment]
***@***.***:/app# ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 Apr27 ?        00:00:00 bash DOfile
root         2     1  0 Apr27 ?        00:00:14 python manage.py qcluster
root        29     2  0 Apr27 ?        00:04:16 python manage.py qcluster
root         3     1  0 Apr27 ?        00:00:30 uwsgi saleor/wsgi/uwsgi.ini
root        30    29  0 Apr27 ?        00:00:00 python manage.py qcluster
root        31    29  0 Apr27 ?        00:00:00 python manage.py qcluster
root        32    29  0 Apr27 ?        00:00:00 python manage.py qcluster
root        33    29  0 Apr27 ?        00:00:00 python manage.py qcluster
root        34    29  0 Apr27 ?        00:00:00 python manage.py qcluster
root        35    29  0 Apr27 ?        00:00:43 python manage.py qcluster
root        64     3  0 05:34 ?        00:00:04 uwsgi saleor/wsgi/uwsgi.ini
root        66     3  0 05:35 ?        00:00:04 uwsgi saleor/wsgi/uwsgi.ini
root        68     3  0 05:35 ?        00:00:04 uwsgi saleor/wsgi/uwsgi.ini
root        71     3  0 10:10 ?        00:00:04 uwsgi saleor/wsgi/uwsgi.ini
root        76     0  0 17:46 ?        00:00:00 bash
root        77    76  0 17:46 ?        00:00:00 ps -ef
***@***.***:/app# python manage.py qinfo
OpenBLAS WARNING - could not determine the L2 cache size on this system,
assuming 256k


  -- Djangorm 1.3.5 on Redis 6.2.1  --

Clusters                        1                               Workers
                    4                               Restarts
         0
Queued                          0                               Successes
                    0                               Failures
         0
Schedules                       0                               Tasks/day
                    0.00                            Avg time
         0.0000
***@***.***:/app#

**Comment by stackbomb** [comment]
Would you mind to share the qcluster configuration? I am using these but no luck:

```
Q_CLUSTER = {
    'name': 'django_q_django',
    'recycle': 200,
    'timeout': 30,
    'compress': True,
    'save_limit': -1,
    'queue_limit': 200,
    'cpu_affinity': 1,
    'label': 'Django Q',
    'redis': REDIS_URL
}
```

Thanks for your precious help!

**Comment by jyoost** [comment]
What version of Django are you using?

When I looked at the above errors on a big screen (not my phone) it looks like errors i got when trying to integrate django_q into an older version of django.  

## Requirements
- Django > = 2.2
- Django-picklefield
- Arrow
- Blessed
Tested with: Python 3.7, 3.8 Django 2.2.X and 3.1.X

**Comment by stackbomb** [comment]
Here is my requirements (part of):

```
Django==3.0.2
django-q==1.2.1
django-redis==4.12.1
arrow==0.15.6
blessed==1.17.5
```

I am trying to upgrade django-q lib, will let you know!

**Comment by jyoost** [comment]
Q_CLUSTER = {
    'name': 'DjangORM',
    'workers': 4,
    'timeout': 90,
    'retry': 120,
    'queue_limit': 50,
    'bulk': 10,
    'redis': REDIS_URL,
}

**Comment by jyoost** [comment]
django-picklefield?

**Comment by stackbomb** [comment]
```
django-picklefield==2.1.1
```

Trying to use your same settings

**Comment by stackbomb** [comment]
Still getting these errors, very strange:

```
worker | 2021-04-28 16:38:02 Traceback (most recent call last):
worker | 2021-04-28 16:38:02   File "manage.py", line 21, in <module>
worker | 2021-04-28 16:38:02     main()
worker | 2021-04-28 16:38:02   File "manage.py", line 17, in main
worker | 2021-04-28 16:38:02     execute_from_command_line(sys.argv)
worker | 2021-04-28 16:38:02   File "/workspace/.heroku/python/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
worker | 2021-04-28 16:38:02     utility.execute()
worker | 2021-04-28 16:38:02   File "/workspace/.heroku/python/lib/python3.7/site-packages/django/core/management/__init__.py", line 395, in execute
worker | 2021-04-28 16:38:02     self.fetch_command(subcommand).run_from_argv(self.argv)
worker | 2021-04-28 16:38:02   File "/workspace/.heroku/python/lib/python3.7/site-packages/django/core/management/base.py", line 328, in run_from_argv
worker | 2021-04-28 16:38:02     self.execute(*args, **cmd_options)
worker | 2021-04-28 16:38:02   File "/workspace/.heroku/python/lib/python3.7/site-packages/django/core/management/base.py", line 369, in execute
worker | 2021-04-28 16:38:02     output = self.handle(*args, **options)
worker | 2021-04-28 16:38:02   File "/workspace/.heroku/python/lib/python3.7/site-packages/django_q/management/commands/qcluster.py", line 22, in handle
worker | 2021-04-28 16:38:02     q.start()
worker | 2021-04-28 16:38:02   File "/workspace/.heroku/python/lib/python3.7/site-packages/django_q/cluster.py", line 53, in start
worker | 2021-04-28 16:38:02     self.stop_event = Event()
worker | 2021-04-28 16:38:02   File "/workspace/.heroku/python/lib/python3.7/multiprocessing/context.py", line 92, in Event
worker | 2021-04-28 16:38:02     return Event(ctx=self.get_context())
worker | 2021-04-28 16:38:02   File "/workspace/.heroku/python/lib/python3.7/multiprocessing/synchronize.py", line 324, in __init__
worker | 2021-04-28 16:38:02     self._cond = ctx.Condition(ctx.Lock())
worker | 2021-04-28 16:38:02   File "/workspace/.heroku/python/lib/python3.7/multiprocessing/context.py", line 67, in Lock
worker | 2021-04-28 16:38:02     return Lock(ctx=self.get_context())
worker | 2021-04-28 16:38:02   File "/workspace/.heroku/python/lib/python3.7/multiprocessing/synchronize.py", line 162, in __init__
worker | 2021-04-28 16:38:02     SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
worker | 2021-04-28 16:38:02   File "/workspace/.heroku/python/lib/python3.7/multiprocessing/synchronize.py", line 59, in __init__
worker | 2021-04-28 16:38:02     unlink_now)
worker | 2021-04-28 16:38:02 OSError: [Errno 38] Function not implemented
worker | 2021-04-28 16:38:02 Sentry is attempting to send 0 pending error messages
worker | 2021-04-28 16:38:02 Waiting up to 2 seconds
worker | 2021-04-28 16:38:02 Press Ctrl-C to quit
```

**Comment by TSolo315** [comment]
I'm having the exact same issue @stackbomb

**Comment by stackbomb** [comment]
@TSolo315 me and the OP are not using docker. The containerization is something that is done automatically by App Platform (@jyoost please change the title in something like "Django Q on digital ocean app platform").
However, I am asking to DO support if they can help me with this issue.

What I've tried so far:
- deployed a super-basic version of Django with Django Q
- running manually `python manage.py qcluster` via UI console
- deployed Django and Django Q as a single DO component
- deployed Django and Django Q as separate DO compontents
- deployed Django and Django Q as a docker image (via Dockerfile, because docker-compose is not supported atm)
Still no luck here. But I'll update this issue to find a way to deploy in a standard way.

**Comment by TSolo315** [comment]
Ah, I was confused. DO app platform does support using a Procfile, not sure if that has been changed since OP posted this. 

I've been (frustratingly) working with support over the past several days about this. Everything points to it being a permissions issue.

https://stackoverflow.com/questions/3314031/django-celery-implementation-oserror-errno-38-function-not-implemented#comment7543003_3699231

https://stackoverflow.com/questions/6033599/oserror-38-errno-38-with-multiprocessing

They told me they would consult the engineering team and get back to me but I'm not particularly optimistic. Not sure why it worked for OP though. Which datacenter region option did you choose @stackbomb? I wonder if that's the difference.

**Comment by stackbomb** [comment]
Yeah, really frustrating. I think App Platform does not support Procfile. This is a reply I got yesterday for DO support:

> Thanks for contacting DigitalOcean.
> 
> I understand you are seeing issues with your worker deploying. It looks like you have made some progress since opening this ticket in your Github post. The example provided there should get that up and running like Jyoost mentions. Though possibly in a future update the Profile method could be supported. 
> 
> Let us know if you have any questions.

BTW, I also think it is an error with permissions, and linked the exact comment you sent lol.
I have tried a $50/mo – Pro 4 GB RAM | 2 vCPUs  x  1 machine in Frankfurt datacenter.

The only person that coul help us to understand better is OP.
OP, could you describe:
- what datacenter are you using
- what machine type are you using

Thank you!

**Comment by TSolo315** [comment]
Procfile is definitely supported (I tested it myself while trying to get this working.)

You have to remove the run command on the web gui or that will take precedence though.

It didn't fix the problem -- worker process set to run qcluster fails silently.

**Comment by stackbomb** [comment]
UPDATE:
It seems that you can't make any fstab change.

> Thanks for getting back to us. Unfortunately it wouldn't be possible to make that fstab change as this is running within a container which doesn't have access to fstab on the host machine. This are isolated environments that don't have full access to fstab.
> We will keep you updated from our engineers as well.

**Comment by jyoost** [comment]
I don't understand what the thread about fstab is.  Can someone please enlighten me?

When running commands inside a docker container, (app platform) you are running as root, so no permission issues.

Docker containers have a transitory file system, disappears with each deploy, or whenever restarted. Anything in container when created stays. Any changes after creation go away at some point. Django_q runs without modifying or needing to modify the file system.

I'm going on 8 days of django project with django_q running a scheduled task every hour on digital ocean app platform.

**Comment by stackbomb** [comment]
It seems related to the multiprocessing error both I and @TSolo315  are getting, `OSError: [Errno 38] Function not implemented`. 

Would you mind to share what datacenter and what machine are you using? We are trying to replicate your setup to understand what's wrong with us.

The problem is that both the deployment and the manual run of the command "python manage.py qcluster" leads to error.

**Comment by Koed00** [comment]
Probably means that the OS used by DO doesn't have a functioning shared semaphore implementation.
That means that Python multiprocessing will not work on it out of the box.
They probably optimized their container OS and omitted shared semaphores. 

You should talk to them if they do support Python Multiprocessing on their platform or if they could.

**Comment by jyoost** [comment]
I will post my Dockerfile in the next post.  It must be doing something to modify the OS put in the container by DO.  All I Know is I have never seen an error like this. I have 2 apps in the DO app platform 1 in NYC NOC and 1 in Singapore NOC

**Comment by jyoost** [comment]
```
FROM python:3.6
ENV PYTHONUNBUFFERED 1

RUN \
  apt-get -y update && \
  apt-get install -y gettext && \
  apt-get install -y uwsgi && \
  apt-get clean

ENV LDFLAGS=-L/usr/lib/x86_64-linux-gnu/

RUN pip3 install --upgrade pip
RUN pip3 install --upgrade setuptools

ADD requirements.txt /app/
RUN pip install -r app/requirements.txt

ADD DOfile /app
ADD . /app

WORKDIR /app

EXPOSE 8000
ENV PORT 8000

CMD ["uwsgi", "/app/djangoadmin/wsgi/uwsgi.ini"]
```

**Comment by TSolo315** [comment]
After several days of asking me try different deployment methods and after I asked them about permissions and shared semaphores the support team finally got back to me with:

> Hello there,
We have an update from our Engineering team. 
We discovered  that multiprocessing pools use a syscall that is not supported by App Platform. We are working on adding support for it but there is no ETA as of now. We have an tracking ticket for that. 

Did you figure out a workaround with a dockerfile @stackbomb?

**Comment by jyoost** [comment]
Did you tell them I have 5 instances running on app platform? 🤓

**Comment by TSolo315** [comment]
No, but they did link me here to try your "DOfile" method -- which had led them to assume multiprocessing was inherently supported. Their support team doesn't really know anything about the limitations of the platform and they rely on googling solutions -- which ends up with them spending six hours only to reply with a suggested solution I had tried days ago before I even contacted them. Rinse and repeat.

My app is using gunicorn instead of uwsgi. Other than your dockerfile idea that's my only other theory for the discrepancy.

**Comment by jyoost** [comment]
😂 I've been on that merry-go-round with them before.

Try the Dockerfile I believe it modifies the os or python.

I'll post my requirements.txt it may install a library at the os level. Since docker runs as root it could modify anything.

**Comment by jyoost** [comment]
aniso8601==7.0.0
arrow==1.0.3
asgiref==3.3.1
beautifulsoup4==4.9.3
blessed==1.18.0
certifi==2020.12.5
chardet==4.0.0
dj-config-url==0.1.1
Django==3.1.7
django-libs==2.0.3

django-picklefield==3.0.1
django-q==1.3.5

idna==2.10
Pillow==8.2.0
promise==2.3
psycopg2-binary==2.8.6
python-dateutil==2.8.1
pytz==2021.1
redis==3.5.3
requests==2.25.1
simplejson==3.17.2
six==1.15.0
soupsieve==2.2
sqlparse==0.4.1
typing-extensions==3.7.4.3
urllib3==1.26.4
uWSGI==2.0.15
wcwidth==0.2.5

**Comment by TSolo315** [comment]
Well,  deploying via dockerfile did not fix the problem (but was educational.)
Neither did switching from gunicorn to uwsgi.

I'll try adding a few of the packages we didn't have in common but I'm on the verge of giving this up.

**Comment by jyoost** [comment]
@TSolo315  that is too bad.  Digital ocean needs to get better support for the app platform.

**Comment by lmmentel** [comment]
Don't know if it helps but I have a django setup  with `docker-compose` on Azure with app services and here is a compose file I use:

```yml
version: "3.8"

services:

  app:
    image: unifairegistry.azurecr.io/app:latest
    command: gunicorn --workers 4 --threads 4 -b 0.0.0.0:8000 --worker-tmp-dir /dev/shm --access-logfile '-' --error-logfile '-' -k uvicorn.workers.UvicornWorker config.asgi
    restart: on-failure
    ports:
      - "8000:8000"

  qcluster:
    image: unifairegistry.azurecr.io/app:latest
    command: python manage.py qcluster
    restart: on-failure
    depends_on:
      - app
```

As you can see both services are using the same docker image.

**Comment by Emilianocm23** [comment]
Im also on DigitalOcean App platform, i just added a worker and its not working for me:

Run Command:  python manage.py qcluster

Output:
[django-q] [2022-01-16 05:36:50] sl = self._semlock = _multiprocessing.SemLock(
[django-q] [2022-01-16 05:36:50] OSError: [Errno 38] Function not implemented

Do you know what can i do? i found on stackoverflow that digitalocean app platform doesnt support it

I tried making a bash file and running it from there but its not working

**Comment by jyoost** [comment]
Has to do with OS version and python version in your docker image. post your Dockerfile.

**Comment by Emilianocm23** [comment]
Thanks for your reply, hmm how do i get the dockerfile?

This is the response i got from DO
![image](https://user-images.githubusercontent.com/74161942/149671219-94d9462c-46c9-4f80-9ba0-6728092ca1fd.png)

I might just move to azure

**Comment by jyoost** [comment]
Should be in the root folder of your project.

**Comment by rcostanza** [comment]
Not an update, just a heads up for anyone that stumbles upon this looking for a solution to the `[Errno 38] Function not implemented`:

There were no changes on Digital Ocean's side, so you still can't get Django Q to work on their **app platform**. You might have better luck trying on a droplet instead, but I haven't tried it.

**Comment by alphazwest** [comment]
1/9/2023 Update:

The problem still persists. Django apps requiring the use of multiprocessing do not work on the App Engine. 

For those integrating with Amazon services -- the Boto3 library makes use of that library enough to make it functionally impossible to use the DO App platform in my experience.

I think "No ETA as of now" means "no hold your breath."

**Comment by jyoost** [comment]
My app using Django-Q ran on app platform for a year, never being restarted Django itself was running 4 processes with uwisgi.  How I did it is in this thread.

**Comment by BackSlasher** [comment]
@jyoost, I'm sorry to be a downer but I believe your solution doesn't really work. Using `&`  means that a nonzero exit from the `qcluster` won't crash the container, but I believe it still fails. you just don't know about it.

**Comment by jyoost** [comment]
Believe?  Don't use this solution then. Don't doubt it without proof or a better solution.

You are a downer.

**Comment by BackSlasher** [comment]
Bash script that creates an obviously failing background task, then runs something else:
```
~$ cat /tmp/bla.sh 
python -c 'bla=1/0' &
sleep 10
echo "all is well"
```
Proof that running it exits with 0, meaning the shell detects no problem:
```
~$ bash /tmp/bla.sh; echo $?
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ZeroDivisionError: division by zero
all is well
0
```

Are you sure your background jobs are actually being executed?

**Comment by jyoost** [comment]
Yes, they are running. They ran for a year every hour, no reboots.

Are you sure you read my instructions?

**Comment by BackSlasher** [comment]
Assuming we talk about this:
```
python manage.py qcluster &
uwsgi djangoadmin/wsgi/uwsgi.ini
```
Then yes, I did.

**Comment by minifisk** [comment]
Any news on this?
