### ISSUE TITLE
500 error with no explanation when adding many tasks

### ISSUE THREAD

**Issue by valyagolev** [Koed00/django-q#576]
Version is 1.3.8

Env: Heroku, redis for the tasks

For some reason, when I create "many" tasks – around 30-40 – during one HTTP request (custom code in admin interface), I get a 500 error.

There's no explanation. I couldn't even catch the exception with `try/except`. It just dies and show "Server Error (500)" in the browser, and there's nothing in the logs except things like `[Q] INFO Enqueued 29` for all the previous tasks. But after 30-40 calls to `async_task` it just dies.

**Comment by Koed00** [comment]
Please give a bit more information - like which broker and config settings.
Django-Q has been tested with thousands of tasks in the queue. So either this is a new issue or it is specific to your setup.

**Comment by valyagolev** [comment]
```

Q_CLUSTER = {
    'retry': 400,
    'timeout': 300,
    'redis': os.environ.get('REDIS_URL'),
    'workers': 1,
}
```

There's nothing else non-default in any configs that I'm aware of

**Comment by valyagolev** [comment]
the code is just:

```
    def reload_team_experts_async(self, request, queryset):
        print("reload_team_experts_async | total tasks to enqueue: %i" % len(queryset.exclude(status="STOPPED")))
        for i, team in enumerate(queryset.exclude(status="STOPPED")):
            print("reload_team_experts_async | task", i)
            tasks.reload_team_experts_async(team.id)
#            time.sleep(0.1) # (tried this but it didn't help)

def reload_team_experts_async(team_id):
    async_task('slackbot.tasks.reload_team_experts', team_id)
```

output is:

```
reload_team_experts_async | total tasks to enqueue: 54
reload_team_experts_async | task 0
14:46:19 [Q] INFO Enqueued 1
reload_team_experts_async | task 1
14:46:19 [Q] INFO Enqueued 1
reload_team_experts_async | task 2
14:46:19 [Q] INFO Enqueued 1
reload_team_experts_async | task 3
14:46:19 [Q] INFO Enqueued 1
reload_team_experts_async | task 4
14:46:19 [Q] INFO Enqueued 2
reload_team_experts_async | task 5
14:46:19 [Q] INFO Enqueued 3
reload_team_experts_async | task 6
14:46:19 [Q] INFO Enqueued 4
reload_team_experts_async | task 7
14:46:19 [Q] INFO Enqueued 5
reload_team_experts_async | task 8
14:46:19 [Q] INFO Enqueued 6
reload_team_experts_async | task 9
14:46:19 [Q] INFO Enqueued 7
reload_team_experts_async | task 10
14:46:20 [Q] INFO Enqueued 7
reload_team_experts_async | task 11
14:46:20 [Q] INFO Enqueued 8
reload_team_experts_async | task 12
14:46:20 [Q] INFO Enqueued 9
reload_team_experts_async | task 13
14:46:20 [Q] INFO Enqueued 10
reload_team_experts_async | task 14
14:46:20 [Q] INFO Enqueued 11
reload_team_experts_async | task 15
14:46:20 [Q] INFO Enqueued 12
reload_team_experts_async | task 16
14:46:20 [Q] INFO Enqueued 13
reload_team_experts_async | task 17
14:46:20 [Q] INFO Enqueued 14
reload_team_experts_async | task 18
14:46:20 [Q] INFO Enqueued 15
reload_team_experts_async | task 19
14:46:21 [Q] INFO Enqueued 16
reload_team_experts_async | task 20
14:46:21 [Q] INFO Enqueued 17
reload_team_experts_async | task 21
14:46:21 [Q] INFO Enqueued 18
reload_team_experts_async | task 22
14:46:21 [Q] INFO Enqueued 19
reload_team_experts_async | task 23
14:46:21 [Q] INFO Enqueued 20
reload_team_experts_async | task 24
14:46:21 [Q] INFO Enqueued 21
reload_team_experts_async | task 25
14:46:21 [Q] INFO Enqueued 22
reload_team_experts_async | task 26
14:46:21 [Q] INFO Enqueued 23
reload_team_experts_async | task 27
14:46:21 [Q] INFO Enqueued 24
reload_team_experts_async | task 28
14:46:21 [Q] INFO Enqueued 25
reload_team_experts_async | task 29
```

**Comment by valyagolev** [comment]
I put this into a task and got:

```
15:30:59 [Q] INFO Process-1:1 processing [emma-oscar-virginia-mobile]
15:30:59 [Q] ERROR Failed [tango-seventeen-uncle-comet] - max number of clients reached : Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.8/site-packages/django_q/cluster.py", line 432, in worker
    res = f(*task["args"], **task["kwargs"])
  File "/app/slackbot/tasks.py", line 69, in reload_all_teams_experts_async
    reload_team_experts_async(team.id)
  File "/app/slackbot/tasks.py", line 59, in reload_team_experts_async
    async_task('slackbot.tasks.reload_team_experts', team_id)
  File "/app/.heroku/python/lib/python3.8/site-packages/django_q/tasks.py", line 73, in async_task
    enqueue_id = broker.enqueue(pack)
  File "/app/.heroku/python/lib/python3.8/site-packages/django_q/brokers/redis_broker.py", line 18, in enqueue
    return self.connection.rpush(self.list_key, task)
  File "/app/.heroku/python/lib/python3.8/site-packages/redis/client.py", line 2016, in rpush
    return self.execute_command('RPUSH', name, *values)
  File "/app/.heroku/python/lib/python3.8/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/app/.heroku/python/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/app/.heroku/python/lib/python3.8/site-packages/redis/connection.py", line 567, in connect
    self.on_connect()
  File "/app/.heroku/python/lib/python3.8/site-packages/redis/connection.py", line 643, in on_connect
    auth_response = self.read_response()
  File "/app/.heroku/python/lib/python3.8/site-packages/redis/connection.py", line 739, in read_response
    response = self._parser.read_response()
  File "/app/.heroku/python/lib/python3.8/site-packages/redis/connection.py", line 340, in read_response
    raise error
redis.exceptions.ConnectionError: max number of clients reached```

Seriously? It creates a redis connection for every task scheduled??

**Comment by Koed00** [comment]
It should not, the broker should always try to re-use the connection.
You could try to set up Django-Redis for your cache;  You can then use it's connection pooling.
https://django-q.readthedocs.io/en/latest/configure.html#django-redis

**Comment by Koed00** [comment]
You can also instantiate a broker before your loop using get_broker, and pass it as a keyword argument to the asyn_task in the loop : https://django-q.readthedocs.io/en/latest/tasks.html#broker

**Comment by valyagolev** [comment]
thanks, I'll check this out. I wish that was the default, to reuse the connection... (I used `Iter` for now). I'm also confused why would it just die instead of letting me catch the exception
