### ISSUE TITLE
file not found

### ISSUE THREAD

**Issue by plungerman** [Koed00/django-q#665]
we are using django-q to schedule twilio SMS messages, which works fine but lately we are seeing FileNotFoundError when the scheduled task contains a CSV file that was uploaded containing a bunch of phone numbers. the file clearly exists on the file system, but django-q can't see to find it when it attempts to kick off the scheduled task. here is the error that appears in the Result field of the Failed Tasks model in the django admin:

[Errno 2] No such file or directory: '/path/to/uploaded/files/8b25fe2c4046418b91865454e21e1f2b.csv' : Traceback (most recent call last):
File "/python/venv/path/lib/python3.8/site-packages/django_q/cluster.py", line 432, in worker
res = f(*task["args"], **task["kwargs"])
File "/data2/python_venv/3.8/djtwilio/lib/python3.8/site-packages/djtwilio/core/utils.py", line 95, in send_bulk
with open(bulk.distribution.path, 'r', errors='replace') as csvfile:
FileNotFoundError: [Errno 2] No such file or directory: '/path/to/uploaded/files/8b25fe2c4046418b91865454e21e1f2b.csv'

here you have our settings with redis as the storage:

Q_CLUSTER = {
    'name': 'DJTwilioRedis',
    'workers': 1,
    'timeout': 30000,
    'retry': 240,
    'recycle': 500,
    'queue_limit': 500,
    'save_limit': 250,
    'compress': True,
    'bulk': 10,
    'cpu_affinity': 1,
    'label': 'Django Q',
    'redis': {
        'host': '127.0.0.1',
        'port': 6379,
        'db': 0,
        'password': None,
        'socket_timeout': None,
        'charset': 'utf-8',
        'errors': 'strict',
        'unix_socket_path': None,
    },
}

timeout is so high because we sometimes are sending 3000 to 5000 messages. i realize that retry should be greater than timeout but that does not seem to be the issue at the moment. we are not using any other caching.

lastly, at one point, the problem could be solved by clearing the redis cache with "sudo redis-cli flushall" but that no longer seems to be working.

any thoughts?

thanks in advance.

django version: 3.2.12
django-q: 1.3.5

**Comment by plungerman** [comment]
ok, it turns out that the csv reader bit of code was failing due to a problem detecting the delimiter but for some reason it was reported as FileNotFound. apologies for the noise.
