### ISSUE TITLE
AttributeError: Can't get attribute 'task_func' on <module '__mp_main__' from ./manage.py

### ISSUE THREAD

**Issue by brdacost** [Koed00/django-q#690]
Django 3.2.9
python 3.10.4
django-q 1.3.9
macOS Monterey Version 12.5

Hello, when i run manage.py qcluster i get error, does somebody know what could be source of it and how to resolve it?

```
19:38:41 [Q] INFO Q Cluster harry-high-fanta-mockingbird starting.
19:38:44 [Q] INFO Process-1 guarding cluster harry-high-fanta-mockingbird
19:38:44 [Q] INFO Q Cluster harry-high-fanta-mockingbird running.
19:38:48 [Q] INFO Process-1:1 ready for work at 92075
19:38:48 [Q] INFO Process-1:2 ready for work at 92076
19:38:48 [Q] INFO Process-1:4 ready for work at 92078
19:38:48 [Q] INFO Process-1:3 ready for work at 92077
19:38:48 [Q] INFO Process-1:5 monitoring at 92079
19:38:48 [Q] INFO Process-1:6 pushing tasks at 92080
Process Process-1:6:
Traceback (most recent call last):
  File "/Users/foo/.pyenv/versions/3.10.4/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/foo/.pyenv/versions/3.10.4/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/foo/Library/Caches/pypoetry/virtualenvs/flux-backend-7x6GG3SE-py3.10/lib/python3.10/site-packages/django_q/cluster.py", line 356, in pusher
    task = SignedPackage.loads(task[1])
  File "/Users/foo/Library/Caches/pypoetry/virtualenvs/flux-backend-7x6GG3SE-py3.10/lib/python3.10/site-packages/django_q/signing.py", line 25, in loads
    return signing.loads(
  File "/Users/foo/Library/Caches/pypoetry/virtualenvs/flux-backend-7x6GG3SE-py3.10/lib/python3.10/site-packages/django_q/core_signing.py", line 44, in loads
    return serializer().loads(data)
  File "/Users/foo/Library/Caches/pypoetry/virtualenvs/flux-backend-7x6GG3SE-py3.10/lib/python3.10/site-packages/django_q/signing.py", line 39, in loads
    return pickle.loads(data)
AttributeError: Can't get attribute 'task_func' on <module '__mp_main__' from '/Users/foo/Documents/projects/flux/flux_backend/manage.py'>
19:38:49 [Q] ERROR reincarnated pusher Process-1:6 after sudden death
```

**Comment by msabatier** [comment]
Hi,

It could be that you have created a task passing the function as an object, not the name. If the function definition at the time of the creation of the task references an attribute of a global or local symbol that does not exist anymore at the time the task is run (because you have updated the code and restarted the cluster in between), you could get this kind of error.

Try to delete the faulty task an recreate it.

**Comment by brdacost** [comment]
> have created a task passing the function as an object, not the name. If the function de

I did exactly that and it worked, but I did not know the specific reason for that...I was afraid it could be a side effect of a feature change. But thanks a lot for the explanation, really reassuring it was just an old queued task from another branch :)
