### ISSUE TITLE
ImportError: cannot import name 'baseconv' from 'django.utils'

### ISSUE THREAD

**Issue by henrikzabel** [Koed00/django-q#738]
I just installed the newest Python and Django Version and when I try to start my Django project I get this:

```cmd
Traceback (most recent call last):
  File "C:\Users\Documents\Startups\Projects\project-eleven\backend\manage.py", line 22, in <module>
    main()
  File "C:\Users\Documents\Startups\Projects\project-eleven\backend\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\Henrik\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\management\__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "C:\Users\Henrik\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\management\__init__.py", line 416, in execute
    django.setup()
  File "C:\Users\Henrik\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\Henrik\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\apps\registry.py", line 116, in populate
    app_config.import_models()
  File "C:\Users\Henrik\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\apps\config.py", line 269, in import_models
    self.models_module = import_module(models_module_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Henrik\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\Henrik\AppData\Local\Programs\Python\Python312\Lib\site-packages\django_q\models.py", line 17, in <module>
    from django_q.signing import SignedPackage
  File "C:\Users\Henrik\AppData\Local\Programs\Python\Python312\Lib\site-packages\django_q\signing.py", line 4, in <module>
    from django_q import core_signing as signing
  File "C:\Users\Henrik\AppData\Local\Programs\Python\Python312\Lib\site-packages\django_q\core_signing.py", line 9, in <module>
    from django.utils import baseconv
ImportError: cannot import name 'baseconv' from 'django.utils' (C:\Users\Henrik\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\utils\__init__.py)
```

Before the update of the Python and Django versions everything worked fine.

## Versions
python=3.12
django=5.0.1

**Comment by GDay** [comment]
Please use this version: https://github.com/django-q2/django-q2
I will merge that repo into this when I have a bit of time.
